### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "d62679ac8224412c9618b3547ce535b3",
  "accountNumber": "1000000000",
  "amount": 1000
}

### get balance
GET http://localhost:8080/transaction/d62679ac8224412c9618b3547ce535b3
Accept: application/json
